### ISSUE TITLE
Title is too long (maximum is 256 characters)

### ISSUE THREAD

**Issue by ghost** [Glabs2/CapitalistPigBusinessSimulatorLikePigBusinessLikeBigBusinessStuff#2]
Capitalist stinks

Delete this BigBusinessStuff!!
_Originally posted by @Ty0nline in https://github.com/Glabs2/CapitalistPigBusinessSimulatorLikePigBusinessLikeBigBusinessStuff/issues/1#issuecomment-1002247030_

xxxxxx

**Comment by Llamato** [comment]
Stop spamming my repo!

**Comment by ghost** [comment]
> Capitalist stinks
> 
> Delete this BigBusinessStuff!! _Originally posted by @Ty0nline in [#1 (comment)](https://github.com/Glabs2/CapitalistPigBusinessSimulatorLikePigBusinessLikeBigBusinessStuff/issues/1#issuecomment-1002247030)_

test 2

**Comment by ghost** [comment]
commentary test

**Comment by ghost** [comment]
Github is fun!
